import express from "express"
import dotenv from "dotenv";
import cors from "cors";
import userRoute from "./routes/userRoute.js"
import connectDB from "./config/db/dbConnect.js";
import bodyParser from "body-parser"
import productRouter from "./routes/productRoute.js"

import cartReducer from "./routes/cartRoute.js"
import otpRouter from "./routes/otpRouter.js";
dotenv.config();


const PORT = process.env.PORT || 8000;
const app = express();
app.use(bodyParser.json());
app.use(cors())
//DATABSE CONNECTION
connectDB(null, null);

//middleware
app.use(express.json());

//Load Routes
app.use("/user-api", userRoute);
app.use("/product-api", productRouter);
app.use("/cart-api", cartReducer);
app.use("/otp-api", otpRouter);


//LOAD DEFAULT DATA?

// const wifiProds=[{'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/projector/l/y/5/android-9-0-dolby-audio-dual-wifi-5g-bt5-0-8k-decoding-6d-original-imah49y2rykkdmnf.jpeg?q=70', 'content': {'title': 'Omex Android 9.0 Dolby Audio Dual Wifi 5G BT5.0 8k deco...', 'price': {'sell_price': '₹14,993', 'org_price': '₹33,690', 'discount': '55% off'}, 'clrTitle': 'Black', 'other': ['Bank Offer']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/projector/v/s/d/android-10-wifi-5g-bt-5-1-electronic-focus-6d-keystone-dolby-original-imagxx3swrzayghy.jpeg?q=70', 'content': {'title': 'Omex Android 10.Wifi 5G BT 5.1 Electronic Focus 6D Keys...', 'price': {'sell_price': '₹7,980', 'org_price': '₹22,600', 'discount': '64% off'}, 'clrTitle': 'White', 'other': ['Lowest price since launch']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/projector/m/m/m/-original-imagu892v92agucu.jpeg?q=70', 'content': {'title': 'Egate K9 Pro-Max Automatic Android Full HD Native 1080p...', 'price': {'sell_price': '₹13,990', 'org_price': '₹30,000', 'discount': '53% off'}, 'clrTitle': 'Black', 'other': ['Only 1 left']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/projector/k/i/t/-original-imagu892nxxjtbgj.jpeg?q=70', 'content': {'title': 'Egate i9 Pro-Max (6900 lm / 1 Speaker / Remote Controll...', 'price': {'sell_price': '₹8,890', 'org_price': '₹15,990', 'discount': '44% off'}, 'clrTitle': 'Black', 'other': ['Daily Saver']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/projector/b/4/f/k9-pro-eo9022-10-eo9022-led-projector-egate-original-imah4jyzbwjgsfyt.jpeg?q=70', 'content': {'title': 'Egate K9 Pro / EO9022 (8400 lm / 1 Speaker / Wireless /...', 'price': {'sell_price': '₹9,990', 'org_price': '₹30,000', 'discount': '66% off'}, 'clrTitle': 'White', 'other': ['Only 1 left']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/projector/p/a/d/m4-android-9-0-fhd-hd-new-5g-wifi-bluetooth-youtube-prime-original-imagxcwyw8hcszup.jpeg?q=70', 'content': {'title': 'Omex M4 Android 9.0 FHD HD New 5G Wifi, bluetooth YouTu...', 'price': {'sell_price': '₹9,490', 'org_price': '₹19,800', 'discount': '52% off'}, 'clrTitle': 'White', 'other': ['Daily Saver']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/projector/b/t/9/o9-android-9-0-full-hd-1080p-native-510-ansi-4k-led-13-original-imagwfrjrvvvhyzk.jpeg?q=70', 'content': {'title': 'Egate O9 Zen (9600 lm / 2 Speaker / Wireless / Remote C...', 'price': {'sell_price': '₹16,990', 'org_price': '₹39,990', 'discount': '57% off'}, 'clrTitle': 'Black', 'other': ['No Cost EMI from ₹2,832/month']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/projector/i/6/u/i9-pro-10-ei9027-led-projector-egate-original-imah3tzkr5jkzhyq.jpeg?q=70', 'content': {'title': 'Egate i9 Pro (6900 lm / 1 Speaker / Remote Controller) ...', 'price': {'sell_price': '₹5,990', 'org_price': '₹9,990', 'discount': '40% off'}, 'clrTitle': 'Black', 'other': ['Only 3 left']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/projector/7/i/d/s9-pro-gold-24-eo9025-full-hd-e-gate-original-imah2y6eaa4jwhr9.jpeg?q=70', 'content': {'title': 'Egate S9 Pro Gold (12000 lm / 2 Speaker / Wireless / Re...', 'price': {'sell_price': '₹27,990', 'org_price': '₹39,990', 'discount': '30% off'}, 'clrTitle': 'Black', 'other': ['No Cost EMI from ₹2,333/month']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/projector/o/d/t/i9-pro-max-android-1080p-native-full-hd-300-ansi-android-4k-original-imagzhkn7nghxz8z.jpeg?q=70', 'content': {'title': 'Egate S9 Pro (9000 lm / 1 Speaker / Wireless / Remote C...', 'price': {'sell_price': '₹16,990', 'org_price': '₹30,000', 'discount': '43% off'}, 'clrTitle': 'Blue', 'other': ['Only few left']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/projector/t/r/t/i9-pro-max-fire-tv-stick-certified-netflix-prime-hotstar-more-original-imahy9nysqzkhdef.jpeg?q=70', 'content': {'title': 'Egate i9 Pro Max FTS (6900 lm / 1 Speaker / Remote Cont...', 'price': {'sell_price': '₹11,990', 'org_price': '₹15,999', 'discount': '25% off'}, 'clrTitle': 'Black', 'other': ['Only few left']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/projector/d/r/h/o9-zen-dual-os-auto-lift-projector-750-ansi-with-fts-arc-hdmi-original-imagzpgnvsqh87f3.jpeg?q=70', 'content': {'title': 'Egate O9 Zen Dual OS (9600 lm / Remote Controller) 1080...', 'price': {'sell_price': '₹20,990', 'org_price': '₹39,990', 'discount': '47% off'}, 'clrTitle': 'Black', 'other': ['Only few left']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/projector/6/t/c/s9-pro-10-pre033-full-hd-egate-original-imahysbennhfggfd.jpeg?q=70', 'content': {'title': 'Egate S9 Pro (9000 lm / 1 Speaker / Wireless / Remote C...', 'price': {'sell_price': '₹16,990', 'org_price': '₹30,000', 'discount': '43% off'}, 'clrTitle': 'Blue', 'other': ['Daily Saver']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/projector/g/6/x/o9-pro-gold-20-egp531-full-hd-egate-original-imah4y5ky7aheg9u.jpeg?q=70', 'content': {'title': 'Egate O9 Pro Gold (15000 lm / Remote Controller) Fully ...', 'price': {'sell_price': '₹27,990', 'org_price': '₹45,000', 'discount': '37% off'}, 'clrTitle': 'Black', 'other': ['Only few left']}},
// ]
// const headProds=[{'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/q/m/y/xo3-gaming-earbuds-with-35ms-low-latency-13mm-drivers-50h-original-imagx8hsq7pqftwy.jpeg?q=70', 'content': {'title': 'HOPPUP Predator Xo3 Gaming Earbuds with 35MS Low Latenc...', 'price': {'sell_price': '₹999', 'org_price': '₹4,999', 'discount': '80% off'}, 'clrTitle': 'Yellow, True Wireless', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/r/k/p/xo6-gaming-earbuds-with-35ms-low-latency-rgb-led-13mm-drivers-original-imahfayb8x85j7kv.jpeg?q=70', 'content': {'title': 'HOPPUP Xo6 Gaming Earbuds with 35MS Low Latency, RGB LE...', 'price': {'sell_price': '₹999', 'org_price': '₹4,999', 'discount': '80% off'}, 'clrTitle': 'Red, True Wireless', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/j/j/7/-original-imah3g9s34zppzmt.jpeg?q=70', 'content': {'title': 'boAt Nirvana Ion with 120 Hours Playback & Crystal Bion...', 'price': {'sell_price': '₹1,649', 'org_price': '₹7,990', 'discount': '79% off'}, 'clrTitle': 'Charcoal Black, True Wireless', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/d/q/r/-original-imagp6skt77zsdjt.jpeg?q=70', 'content': {'title': 'Noise Buds VS102 with 50 Hrs Playtime, 11mm Driver, IPX...', 'price': {'sell_price': '₹1,199', 'org_price': '₹2,999', 'discount': '60% off'}, 'clrTitle': 'Midnight Blue, True Wireless', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/v/y/o/-original-imagt3vwuweuwk9v.jpeg?q=70', 'content': {'title': 'realme Buds T300 with 12.4mm Driver, 30dB ANC, 360 Spat...', 'price': {'sell_price': '₹1,999', 'org_price': '₹3,999', 'discount': '50% off'}, 'clrTitle': 'Stylish Black, True Wireless', 'other': ['Daily Saver']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/u/k/c/predator-xo4-gaming-earbuds-with-35ms-low-latency-50h-playtime-original-imagvfsmmzennwvs.jpeg?q=70', 'content': {'title': 'HOPPUP Predator Xo4 Gaming Earbuds with 35MS Low Latenc...', 'price': {'sell_price': '₹799', 'org_price': '₹4,999', 'discount': '84% off'}, 'clrTitle': 'Blue, True Wireless', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/q/m/s/-original-imah3zvdthupfejc.jpeg?q=70', 'content': {'title': 'boAt Airdopes 161/163 with ASAP Charge & 40 HRS Playbac...', 'price': {'sell_price': '₹1,099', 'org_price': '₹2,490', 'discount': '55% off'}, 'clrTitle': 'Pebble Black, Active Black, True Wireless', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/t/t/r/tf-premium-bth-f9-earbuds-tws-buds-5-1-earbuds-with-280h-original-imah2sdzjdq8yxjn.jpeg?q=70', 'content': {'title': 'HODOPHILE TF Premium BTH F9 Earbuds/TWs/buds 5.1 Earbud...', 'price': {'sell_price': '₹649', 'org_price': '₹2,499', 'discount': '74% off'}, 'clrTitle': 'Black, True Wireless', 'other': ['Only few left']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/w/t/q/-original-imagr4t8zuq2wzhe.jpeg?q=70', 'content': {'title': 'OnePlus Nord Buds 2r in Ear Earbuds with Dual Mic & AI ...', 'price': {'sell_price': '₹1,999', 'org_price': '₹2,299', 'discount': '13% off'}, 'clrTitle': 'Deep Grey, True Wireless', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/y/a/n/-original-imagqcw5h8ahyhgf.jpeg?q=70', 'content': {'title': 'boAt Airdopes 131 PRO with 11mm Drivers,45Hrs Playback,...', 'price': {'sell_price': '₹899', 'org_price': '₹2,990', 'discount': '69% off'}, 'clrTitle': 'Royal Blue, True Wireless', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/7/j/4/airdoze-s40-earbuds-with-13mm-drivers-40h-playtime-rage-mode-enc-original-imagrzkxqwnxn9ac.jpeg?q=70', 'content': {'title': 'HOPPUP AirDoze S40 Earbuds with 13MM Drivers, 40H Playt...', 'price': {'sell_price': '₹699', 'org_price': '₹3,999', 'discount': '82% off'}, 'clrTitle': 'Blue, True Wireless', 'other': ['Daily Saver']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/7/n/g/air-buds-pro-e35-50hrs-battery-life-high-bass-mic-ai-enc-touch-original-imah3hzedwv8fpqy.jpeg?q=70', 'content': {'title': 'Microflash Air Buds Pro E35 50Hrs Battery Life, High Ba...', 'price': {'sell_price': '₹659', 'org_price': '₹1,999', 'discount': '67% off'}, 'clrTitle': 'Black, True Wireless', 'other': ['Bank Offer']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/s/7/f/-original-imahf4qppx6fkxtw.jpeg?q=70', 'content': {'title': 'Boult Y1 Pro with Zen Quad Mic ENC, 60Hrs Battery, Fast...', 'price': {'sell_price': '₹1,199', 'org_price': '₹5,999', 'discount': '80% off'}, 'clrTitle': 'Powder Blue, True Wireless', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/b/r/e/blue-wireless-ear-buds-witth-multiple-features-brolan-original-imah2gtygcjh8fhs.jpeg?q=70', 'content': {'title': 'Brolan Blue Wireless Ear Buds witth multiple features B...', 'price': {'sell_price': '₹748', 'org_price': '₹2,299', 'discount': '67% off'}, 'clrTitle': 'Blue, True Wireless', 'other': ['Only few left']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/f/y/f/-original-imahy3uqgtzmdsge.jpeg?q=70', 'content': {'title': 'realme Buds T110 with AI ENC for calls, upto 38 hours o...', 'price': {'sell_price': '₹1,499', 'org_price': '₹2,999', 'discount': '50% off'}, 'clrTitle': 'Punk Black, True Wireless', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/v/k/v/-original-imah3am86gzrvr6g.jpeg?q=70', 'content': {'title': 'TRIGGR Ultrabuds N1 Neo with ENC, 40Hr Playback, 13mm D...', 'price': {'sell_price': '₹699', 'org_price': '₹2,999', 'discount': '76% off'}, 'clrTitle': 'Sky Black, True Wireless', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/t/o/z/air-buds-pro-e35-50hrs-battery-life-high-bass-mic-ai-enc-touch-original-imah3hzdzctu4jnj.jpeg?q=70', 'content': {'title': 'Microflash Air Buds Pro E35 50Hrs Battery Life, High Ba...', 'price': {'sell_price': '₹659', 'org_price': '₹1,999', 'discount': '67% off'}, 'clrTitle': 'Blue, True Wireless', 'other': ['Bank Offer']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/r/x/g/predator-xo4-gaming-earbuds-with-35ms-low-latency-50h-playtime-original-imagvfsnszzzzztj.jpeg?q=70', 'content': {'title': 'HOPPUP Predator Xo4 Gaming Earbuds with 35MS Low Latenc...', 'price': {'sell_price': '₹799', 'org_price': '₹4,999', 'discount': '84% off'}, 'clrTitle': 'White, True Wireless', 'other': ['Bank Offer']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/a/5/0/-original-imahy3uqdmgx6qey.jpeg?q=70', 'content': {'title': 'realme Buds T110 with AI ENC for calls, upto 38 hours o...', 'price': {'sell_price': '₹1,499', 'org_price': '₹2,999', 'discount': '50% off'}, 'clrTitle': 'Jazz Blue, True Wireless', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/u/v/0/-original-imahyfkkyamsjxn8.jpeg?q=70', 'content': {'title': 'CMF by Nothing Buds 42 dB Active Noise Cancellation, Ul...', 'price': {'sell_price': '₹2,499', 'org_price': '₹2,999', 'discount': '16% off'}, 'clrTitle': 'Dark Grey, True Wireless', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/p/c/n/airdoze-s40-earbuds-with-13mm-drivers-40h-playtime-rage-mode-enc-original-imah2srqqycdu36y.jpeg?q=70', 'content': {'title': 'HOPPUP AirDoze S40 Earbuds with 13MM Drivers, 40H Playt...', 'price': {'sell_price': '₹699', 'org_price': '₹3,999', 'discount': '82% off'}, 'clrTitle': 'Black, True Wireless', 'other': ['Daily Saver']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/w/p/m/-original-imagrvmgmhdk6msy.jpeg?q=70', 'content': {'title': 'Mivi DuoPods D3 TWS,13mm Driver,Rich Bass,50H Playtime,...', 'price': {'sell_price': '₹799', 'org_price': '₹2,999', 'discount': '73% off'}, 'clrTitle': 'Cobalt Black, True Wireless', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/x/4/9/-original-imagtr2nezygmu4f.jpeg?q=70', 'content': {'title': 'Boult Z40 Pro with 100H Battery, Quad Mic ENC, Scratch ...', 'price': {'sell_price': '₹1,499', 'org_price': '₹5,499', 'discount': '72% off'}, 'clrTitle': 'Midnight, True Wireless', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/k/z/m/buds-f1-ultra-truke-original-imagy2n2mmadjgpx.jpeg?q=70', 'content': {'title': 'truke Buds F1 Ultra with 60 Hours Playtime, Spatial Aud...', 'price': {'sell_price': '₹798', 'org_price': '₹2,999', 'discount': '73% off'}, 'clrTitle': 'Black, True Wireless', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/c/6/a/-original-imahyrha4unythg4.jpeg?q=70', 'content': {'title': 'boAt Immortal 161 w/ Beast Mode(40ms Low Latency), 40 H...', 'price': {'sell_price': '₹999', 'org_price': '₹3,499', 'discount': '71% off'}, 'clrTitle': 'Black Sabre, True Wireless', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/h/e/h/buds-3-e509a-oneplus-original-imagwynyzms78bsg.jpeg?q=70', 'content': {'title': 'OnePlus Buds 3 TWS, in Ear Earbuds with Sliding Volume ...', 'price': {'sell_price': '₹5,499', 'org_price': '₹6,499', 'discount': '15% off'}, 'clrTitle': 'Metallic Gray IN, True Wireless', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/h/y/k/gaming-theta-dual-mode-upto-150hrs-standby-400mah-battery-rgb-45-original-imah44dgveggafkx.jpeg?q=70', 'content': {'title': 'Grooves Gaming Theta,Dual Mode,Upto 150hrs StandBy,400m...', 'price': {'sell_price': '₹1,499', 'org_price': '₹3,999', 'discount': '62% off'}, 'clrTitle': 'Grey, True Wireless', 'other': ['Daily Saver']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/h/g/u/xo3-gaming-earbuds-with-35ms-low-latency-13mm-drivers-50h-original-imagx8hzzxrrg235.jpeg?q=70', 'content': {'title': 'HOPPUP Predator Xo3 Gaming Earbuds with 35MS Low Latenc...', 'price': {'sell_price': '₹999', 'org_price': '₹4,999', 'discount': '80% off'}, 'clrTitle': 'White, True Wireless', 'other': ['Bank Offer']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/m/x/o/-original-imagt5cwzxknqpbu.jpeg?q=70', 'content': {'title': 'Boult W20 with Zen ENC Mic, 35H Battery Life, Low Laten...', 'price': {'sell_price': '₹1,099', 'org_price': '₹2,499', 'discount': '56% off'}, 'clrTitle': 'Glacier Blue, True Wireless', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/l/p/4/-original-imagtvqpkzkedv8p.jpeg?q=70', 'content': {'title': 'Boult Y1 with Zen ENC Mic, 50H Battery, Fast Charging, ...', 'price': {'sell_price': '₹999', 'org_price': '₹5,499', 'discount': '81% off'}, 'clrTitle': 'Black, True Wireless', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/3/g/3/air-buds-d79-upto-30hrs-playback-13mm-driver-true-wireless-original-imah25j4zkfdytb6.jpeg?q=70', 'content': {'title': 'Microflash Air Buds-D79 Upto 30Hrs Playback 13mm Driver...', 'price': {'sell_price': '₹634', 'org_price': '₹1,999', 'discount': '68% off'}, 'clrTitle': 'Black, True Wireless', 'other': ['Bank Offer']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/y/m/y/-original-imah3aj4tkzkgc5y.jpeg?q=70', 'content': {'title': 'vivo TWS 3e buds up-to 30dB Active Noise Cancellation |...', 'price': {'sell_price': '₹1,899', 'org_price': '₹2,499', 'discount': '24% off'}, 'clrTitle': 'Bright White, True Wireless', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/6/s/j/-original-imahyz8hgbgkyrdd.jpeg?q=70', 'content': {'title': 'Noise Buds VS102 Neo with 40 Hrs Playtime, Environmenta...', 'price': {'sell_price': '₹999', 'org_price': '₹3,499', 'discount': '71% off'}, 'clrTitle': 'Carbon Black, True Wireless', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/p/r/z/enco-buds-2-oppo-original-imagh9frfp7gxdb3.jpeg?q=70', 'content': {'title': 'OPPO Enco Buds 2 with 28 hours Battery life & Deep Nois...', 'price': {'sell_price': '₹1,799', 'org_price': '₹3,999', 'discount': '55% off'}, 'clrTitle': 'Midnight, True Wireless', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/k/i/o/-original-imagp6skdxptyrjt.jpeg?q=70', 'content': {'title': 'Noise Buds VS102 with 50 Hrs Playtime, 11mm Driver, IPX...', 'price': {'sell_price': '₹1,199', 'org_price': '₹2,999', 'discount': '60% off'}, 'clrTitle': 'Celeste Blue, True Wireless', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/o/z/8/-original-imagtr2n2wzggxuh.jpeg?q=70', 'content': {'title': 'Boult Z40 Pro with 100H Battery, Quad Mic ENC, Scratch ...', 'price': {'sell_price': '₹1,499', 'org_price': '₹5,499', 'discount': '72% off'}, 'clrTitle': 'Jungle, True Wireless', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/1/w/f/predator-xo7-gaming-earbuds-with-35ms-low-latency-13mm-drivers-original-imah2tvtdbnsnfxg.jpeg?q=70', 'content': {'title': 'HOPPUP Predator Xo7 Gaming Earbuds with 35MS Low Latenc...', 'price': {'sell_price': '₹899', 'org_price': '₹5,999', 'discount': '85% off'}, 'clrTitle': 'Black, Grey, True Wireless', 'other': ['Bank Offer']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/m/s/s/-original-imah34qc6vptzasv.jpeg?q=70', 'content': {'title': 'Mivi DuoPods i6 TWS, Engineered for Athletes, IPX 4.0,1...', 'price': {'sell_price': '₹1,199', 'org_price': '₹3,499', 'discount': '65% off'}, 'clrTitle': 'Beige, True Wireless', 'other': ['Bank Offer']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/p/0/p/-original-imagp6skfbnypq5g.jpeg?q=70', 'content': {'title': 'Noise Buds VS102 with 50 Hrs Playtime, 11mm Driver, IPX...', 'price': {'sell_price': '₹1,199', 'org_price': '₹2,999', 'discount': '60% off'}, 'clrTitle': 'Jet Black, True Wireless', 'other': ['Daily Saver']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/3/k/k/-original-imah45q9zpkxdc7a.jpeg?q=70', 'content': {'title': 'Number SuperBuds 555 with Dual Pair, 66H Battery, 32dB ...', 'price': {'sell_price': '₹1,499', 'org_price': '₹7,999', 'discount': '81% off'}, 'clrTitle': 'Blue Lava, True Wireless', 'other': ['Bank Offer']}},
// ]
// const blutoohProds=[{'url': 'https://rukminim2.flixcart.com/image/612/612/kiqbma80-0/speaker/mobile-tablet-speaker/j/e/m/bs5rm2-bl-mivi-original-imafyg8xesq4hyzz.jpeg?q=70', 'content': {'title': 'Mivi Roam2 5 W Bluetooth Speaker', 'price': {'sell_price': '₹899', 'org_price': '₹2,999', 'discount': '70% off'}, 'clrTitle': 'Blue, Mono Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/m/n/x/-original-imah4jfdjj6g3jrn.jpeg?q=70', 'content': {'title': 'Mivi Fort H120 Soundbar, 120 Watts, 2.1 Channel, Multi-...', 'price': {'sell_price': '₹5,999', 'org_price': '₹19,999', 'discount': '70% off'}, 'clrTitle': 'Black, 5.1 Channel', 'other': ['No Cost EMI from ₹1,000/month']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/p/q/z/-original-imahfzk6gwwtpqv3.jpeg?q=70', 'content': {'title': 'ZEBRONICS Juke bar 4000 120 W Bluetooth Soundbar', 'price': {'sell_price': '₹4,999', 'org_price': '₹14,999', 'discount': '66% off'}, 'clrTitle': 'Black, 2.1 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/m/h/s/-original-imaggrf8mfkyyvvj.jpeg?q=70', 'content': {'title': 'Mivi Fort S16 with 2 full range drivers, Made in India ...', 'price': {'sell_price': '₹1,099', 'org_price': '₹2,999', 'discount': '63% off'}, 'clrTitle': 'Black, 2.0 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/l/b/h/-original-imagpjxr9zp8ayhw.jpeg?q=70', 'content': {'title': 'boAt Aavante Bar Chord with Wireless Subwoofer and Dyna...', 'price': {'sell_price': '₹6,999', 'org_price': '₹22,990', 'discount': '69% off'}, 'clrTitle': 'Premium Black, 2.1 Channel', 'other': ['No Cost EMI from ₹1,167/month']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/2/h/5/-original-imagxxbgy3quchtg.jpeg?q=70', 'content': {'title': 'Mivi Fort S250 With wireless Subwoofer,Sound, BT v5.3 2...', 'price': {'sell_price': '₹7,999', 'org_price': '₹22,999', 'discount': '65% off'}, 'clrTitle': 'Black, 2.1 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/kplisnk0/speaker/mobile-tablet-speaker/8/k/e/bs5pl-bk-mivi-original-imag3sgmv9hzrncf.jpeg?q=70', 'content': {'title': 'Mivi Play 5 W Portable Bluetooth Speaker', 'price': {'sell_price': '₹799', 'org_price': '₹1,999', 'discount': '60% off'}, 'clrTitle': 'Black, Mono Channel', 'other': ['Daily Saver']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/l0r1j0w0/speaker/8/s/w/-original-imagch7jzhc2yefp.jpeg?q=70', 'content': {'title': 'Mivi Fort S60 with 2 in-built subwoofers, Made in India...', 'price': {'sell_price': '₹2,799', 'org_price': '₹6,999', 'discount': '60% off'}, 'clrTitle': 'Black, 2.2 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/k5vcya80pkrrdj/speaker/laptop-desktop-speaker/c/t/z/zebronics-fame-2-0-channel-original-imafkjb9pesgmyzw.jpeg?q=70', 'content': {'title': 'ZEBRONICS Zeb - Fame 5 watt Laptop/Desktop Speaker', 'price': {'sell_price': '₹599', 'org_price': '₹849', 'discount': '29% off'}, 'clrTitle': 'Black, 2.0 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/mobile-tablet-speaker/e/f/j/por-1578-portronics-original-imagtaf2d2w3f4ry.jpeg?q=70', 'content': {'title': 'Portronics SoundDrum P Wireless with 6-7 hrs Playback T...', 'price': {'sell_price': '₹2,098', 'org_price': '₹3,499', 'discount': '40% off'}, 'clrTitle': 'Black, Stereo Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/w/h/h/-original-imagszffs7jzyp6f.jpeg?q=70', 'content': {'title': 'GOVO GOSURROUND 200 |2000 mAh Battery 16 W Bluetooth Sp...', 'price': {'sell_price': '₹1,199', 'org_price': '₹3,999', 'discount': '70% off'}, 'clrTitle': 'Platinum Black, 2.0 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/kiqbma80-0/speaker/mobile-tablet-speaker/u/s/g/bs5rm2-bk-mivi-original-imafyg8xbv9rfsnn.jpeg?q=70', 'content': {'title': 'Mivi Roam2 5 W Bluetooth Speaker', 'price': {'sell_price': '₹899', 'org_price': '₹2,999', 'discount': '70% off'}, 'clrTitle': 'Black, Mono Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/u/f/k/-original-imagtevgtbtauah7.jpeg?q=70', 'content': {'title': 'boAt Stone 350 Hulk Edition 10 W Bluetooth Speaker', 'price': {'sell_price': '₹1,699', 'org_price': '₹3,490', 'discount': '51% off'}, 'clrTitle': 'Green Fury, Mono Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/j/q/v/-original-imagtnpuctjgnzrx.jpeg?q=70', 'content': {'title': 'boAt Aavante Bar 3500 with Bass & Treble Controls, EQ M...', 'price': {'sell_price': '₹13,999', 'org_price': '₹44,990', 'discount': '68% off'}, 'clrTitle': 'Premium Black, 5.1 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/kingqkw0-0/speaker/mobile-tablet-speaker/s/8/i/stone-350-boat-original-imafyebfuaumdezs.jpeg?q=70', 'content': {'title': 'boAt Stone 350 10 W Bluetooth Speaker', 'price': {'sell_price': '₹1,699', 'org_price': '₹3,490', 'discount': '51% off'}, 'clrTitle': 'Black, Mono Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/s/g/e/-original-imahy4y8heh2dbbr.jpeg?q=70', 'content': {'title': 'boAt Aavante Bar A1040 w/ Attractive Design, EQ Modes &...', 'price': {'sell_price': '₹3,999', 'org_price': '₹9,990', 'discount': '59% off'}, 'clrTitle': 'Premium Black, 2.1 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/v/o/a/-original-imah4jfdkdxnk2fg.jpeg?q=70', 'content': {'title': 'Mivi Fort H160 Soundbar, 160 Watts, 2.1 Channel, Multi-...', 'price': {'sell_price': '₹8,999', 'org_price': '₹25,999', 'discount': '65% off'}, 'clrTitle': 'Black, 5.1 Channel', 'other': ['No Cost EMI from ₹1,500/month']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/kiqbma80-0/speaker/mobile-tablet-speaker/j/l/p/bs5rm2-gn-mivi-original-imafyg8xdakhggu2.jpeg?q=70', 'content': {'title': 'Mivi Roam2 5 W Bluetooth Speaker', 'price': {'sell_price': '₹1,198', 'org_price': '₹2,999', 'discount': '60% off'}, 'clrTitle': 'Green, Mono Channel', 'other': ['Bank Offer']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/mobile-tablet-speaker/s/w/n/por-1578-portronics-original-imagtq36fg6sxzn9.jpeg?q=70', 'content': {'title': 'Portronics SoundDrum P Wireless with 6-7 hrs Playback T...', 'price': {'sell_price': '₹2,399', 'org_price': '₹3,999', 'discount': '40% off'}, 'clrTitle': 'Green, Stereo Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/laptop-desktop-speaker/c/i/z/zeb-warrior-zebronics-original-imah43f5jnzzhzsu.jpeg?q=70', 'content': {'title': 'ZEBRONICS ZEB-WARRIOR 10 W Laptop/Desktop Speaker', 'price': {'sell_price': '₹699', 'org_price': '₹1,249', 'discount': '44% off'}, 'clrTitle': 'Black, Black, 2.0 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/u/o/8/-original-imah2ggehx5ggumz.jpeg?q=70', 'content': {'title': 'Mivi Fort S38 With Sub woofer, 38W, BT v5.3, Surround S...', 'price': {'sell_price': '₹2,299', 'org_price': '₹10,999', 'discount': '79% off'}, 'clrTitle': 'Black, 2.1 Channel', 'other': ['Lowest price since launch']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/kiqbma80-0/speaker/mobile-tablet-speaker/k/4/j/bs5rm2-rd-mivi-original-imafyg8xtrt4tywk.jpeg?q=70', 'content': {'title': 'Mivi Roam2 5 W Bluetooth Speaker', 'price': {'sell_price': '₹1,199', 'org_price': '₹2,999', 'discount': '60% off'}, 'clrTitle': 'Red, Mono Channel', 'other': ['Bank Offer']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/r/z/s/-original-imagz9cn93exxyrj.jpeg?q=70', 'content': {'title': 'boAt Aavante Bar 590 with RMS, Dual Passive Radiatior &...', 'price': {'sell_price': '₹1,999', 'org_price': '₹5,990', 'discount': '66% off'}, 'clrTitle': 'Pebble Black, 2.0 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/c/v/v/-original-imah4gpechxzhd9c.jpeg?q=70', 'content': {'title': 'boAt Aavante Bar 520 w/ Dual Passive Radiators,6 HRS Pl...', 'price': {'sell_price': '₹1,699', 'org_price': '₹3,990', 'discount': '57% off'}, 'clrTitle': 'Charcoal Black, 2.0 Channel', 'other': ['Daily Saver']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/kpzt7680/speaker/mobile-tablet-speaker/c/7/o/sounddrum-1-por-1327-portronics-original-imag43tcuz8swymc.jpeg?q=70', 'content': {'title': 'Portronics SoundDrum 1 10W TWS Portable, Inbuilt-FM & T...', 'price': {'sell_price': '₹1,199', 'org_price': '₹2,499', 'discount': '52% off'}, 'clrTitle': 'Blue, Mono Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/kmkxbww0/speaker/laptop-desktop-speaker/7/x/u/warrior-ii-2-0-channel-usb-speaker-led-lights-with-usb-powered-original-imagfg3h9azuzsxt.jpeg?q=70', 'content': {'title': 'ZEBRONICS WARRIOR II USB , LED LIGHTS WITH POWERED AND ...', 'price': {'sell_price': '₹649', 'org_price': '₹1,399', 'discount': '53% off'}, 'clrTitle': 'Black, 2.0 Channel', 'other': ['Daily Saver']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/t/b/y/-original-imah4d3shajmeddh.jpeg?q=70', 'content': {'title': 'Mivi Fort H550 Soundbar, 550 Watts, 5.1 Channel, Multi-...', 'price': {'sell_price': '₹9,999', 'org_price': '₹39,999', 'discount': '75% off'}, 'clrTitle': 'Black, 5.1 Channel', 'other': ['No Cost EMI from ₹1,667/month']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/shopsy-speaker/9/x/b/yes-16-soundbar-pro-surround-hd-sound-c-type-16-watt-1500mah-original-imahfyqtjmpfrbma.jpeg?q=70', 'content': {'title': 'MEGABAR Soundbar Pro 16W Speaker Party Light Speaker Wa...', 'price': {'sell_price': '₹899', 'org_price': '₹2,599', 'discount': '65% off'}, 'clrTitle': 'Black, 5.2 Channel', 'other': ['Lowest Price in 30 days']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/b/1/d/-original-imagqd2dzewdheez.jpeg?q=70', 'content': {'title': "GOVO GOSURROUND 900 |200W | 2.1 with 6.5'' Wired Subwoo...", 'price': {'sell_price': '₹6,599', 'org_price': '₹17,999', 'discount': '63% off'}, 'clrTitle': 'Platinum Black, 2.1 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/kingqkw0-0/speaker/mobile-tablet-speaker/u/1/2/stone-350-boat-original-imafyebfjguufap8.jpeg?q=70', 'content': {'title': 'boAt Stone 350 10 W Bluetooth Speaker', 'price': {'sell_price': '₹1,699', 'org_price': '₹3,490', 'discount': '51% off'}, 'clrTitle': 'Blue, Mono Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/k/x/s/-original-imagszffm6qygvgb.jpeg?q=70', 'content': {'title': "GOVO GOSURROUND 750 |with 5.25'' Wired Subwoofer 120 W ...", 'price': {'sell_price': '₹5,499', 'org_price': '₹15,999', 'discount': '65% off'}, 'clrTitle': 'Platinum Black, 2.1 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/l0r1j0w0/speaker/u/s/u/-original-imagch7jmd9c9v7e.jpeg?q=70', 'content': {'title': 'Mivi Fort S100 with 2 in-built subwoofers, Made in Indi...', 'price': {'sell_price': '₹5,499', 'org_price': '₹9,999', 'discount': '45% off'}, 'clrTitle': 'Black, 2.2 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/y/r/i/-original-imagt4wcgmzdrhqv.jpeg?q=70', 'content': {'title': 'boAt Aavante Bar 480 with 7 HRS Playback, Dual Full Ran...', 'price': {'sell_price': '₹1,399', 'org_price': '₹3,490', 'discount': '59% off'}, 'clrTitle': 'Black, 2.0 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/x/q/b/-original-imah2d55jusy9p9t.jpeg?q=70', 'content': {'title': 'boAt Stone 350 Pro w/ Dynamic RGB LEDs, 12 HRS Playback...', 'price': {'sell_price': '₹1,999', 'org_price': '₹4,990', 'discount': '59% off'}, 'clrTitle': 'Raging Black, Mono Channel', 'other': ['Bank Offer']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/s/c/u/-original-imagg33vchvr6fw3.jpeg?q=70', 'content': {'title': 'Mivi Fort S200 with wired subwoofer, Made in India 200 ...', 'price': {'sell_price': '₹5,999', 'org_price': '₹19,999', 'discount': '70% off'}, 'clrTitle': 'Black, 2.1 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/kingqkw0-0/speaker/mobile-tablet-speaker/r/b/4/stone-350-boat-original-imafyebgtg74sghe.jpeg?q=70', 'content': {'title': 'boAt Stone 350 10 W Bluetooth Speaker', 'price': {'sell_price': '₹1,699', 'org_price': '₹3,490', 'discount': '51% off'}, 'clrTitle': 'Red, Mono Channel', 'other': ['Bank Offer']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/s/4/6/-original-imagz6kn77uzz9t3.jpeg?q=70', 'content': {'title': 'SONY HT-S20R 5.1ch Home Theatre with Dolby Digital, Sub...', 'price': {'sell_price': '₹17,190', 'org_price': '₹19,990', 'discount': '14% off'}, 'clrTitle': 'Black, 5.1 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/kplisnk0/speaker/mobile-tablet-speaker/8/t/m/bs5pl-bl-mivi-original-imag3sgm77an79j7.jpeg?q=70', 'content': {'title': 'Mivi Play 5 W Portable Bluetooth Speaker', 'price': {'sell_price': '₹799', 'org_price': '₹1,999', 'discount': '60% off'}, 'clrTitle': 'Blue, Mono Channel', 'other': ['Daily Saver']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/n/s/7/-original-imah2d55jh6ryzjz.jpeg?q=70', 'content': {'title': 'boAt Stone 350 Pro w/ Dynamic RGB LEDs, 12 HRS Playback...', 'price': {'sell_price': '₹1,999', 'org_price': '₹4,990', 'discount': '59% off'}, 'clrTitle': 'Vibing Blue, Mono Channel', 'other': ['Bank Offer']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/k0vbgy80pkrrdj/speaker-refurbished/g/q/v/b-lk72b-lg-original-imafkdw5cz6ehgbu.jpeg?q=70', 'content': {'title': 'LG LK72B, Deep Bass, USB, SD Card and FM Radio 40 W Blu...', 'price': {'sell_price': '₹4,690', 'org_price': '₹4,990', 'discount': '6% off'}, 'clrTitle': 'Black, 2.1 Channel', 'other': ['Save extra with combo offers']}},
// ]
//  const tempProds=[{'url': 'https://rukminim2.flixcart.com/image/612/612/kiqbma80-0/speaker/mobile-tablet-speaker/j/e/m/bs5rm2-bl-mivi-original-imafyg8xesq4hyzz.jpeg?q=70', 'content': {'title': 'Mivi Roam2 5 W Bluetooth Speaker', 'price': {'sell_price': '₹899', 'org_price': '₹2,999', 'discount':"70% off"}, 'clrTitle': 'Blue, Mono Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/w/h/h/-original-imagszffs7jzyp6f.jpeg?q=70', 'content': {'title': 'GOVO GOSURROUND 200 |2000 mAh Battery 16 W Bluetooth Sp...', 'price': {'sell_price': '₹1,199', 'org_price': '₹3,999', 'discount':"70% off"}, 'clrTitle': 'Platinum Black, 2.0 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/p/q/z/-original-imahfzk6gwwtpqv3.jpeg?q=70', 'content': {'title': 'ZEBRONICS Juke bar 4000 120 W Bluetooth Soundbar', 'price': {'sell_price': '₹4,999', 'org_price': '₹14,999', 'discount':"66% off"}, 'clrTitle': 'Black, 2.1 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/m/h/s/-original-imaggrf8mfkyyvvj.jpeg?q=70', 'content': {'title': 'Mivi Fort S16 with 2 full range drivers, Made in India ...', 'price': {'sell_price': '₹1,099', 'org_price': '₹2,999', 'discount':"63% off"}, 'clrTitle': 'Black, 2.0 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/l/b/h/-original-imagpjxr9zp8ayhw.jpeg?q=70', 'content': {'title': 'boAt Aavante Bar Chord with Wireless Subwoofer and Dyna...', 'price': {'sell_price': '₹6,999', 'org_price': '₹22,990', 'discount':"69% off"}, 'clrTitle': 'Premium Black, 2.1 Channel', 'other': ['No Cost EMI from ₹1,167/month']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/2/h/5/-original-imagxxbgy3quchtg.jpeg?q=70', 'content': {'title': 'Mivi Fort S250 With wireless Subwoofer,Sound, BT v5.3 2...', 'price': {'sell_price': '₹7,999', 'org_price': '₹22,999', 'discount':"65% off"}, 'clrTitle': 'Black, 2.1 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/kplisnk0/speaker/mobile-tablet-speaker/8/k/e/bs5pl-bk-mivi-original-imag3sgmv9hzrncf.jpeg?q=70', 'content': {'title': 'Mivi Play 5 W Portable Bluetooth Speaker', 'price': {'sell_price': '₹799', 'org_price': '₹1,999', 'discount':"60% off"}, 'clrTitle': 'Black, Mono Channel', 'other': ['Daily Saver']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/l0r1j0w0/speaker/8/s/w/-original-imagch7jzhc2yefp.jpeg?q=70', 'content': {'title': 'Mivi Fort S60 with 2 in-built subwoofers, Made in India...', 'price': {'sell_price': '₹2,799', 'org_price': '₹6,999', 'discount':"60% off"}, 'clrTitle': 'Black, 2.2 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/k5vcya80pkrrdj/speaker/laptop-desktop-speaker/c/t/z/zebronics-fame-2-0-channel-original-imafkjb9pesgmyzw.jpeg?q=70', 'content': {'title': 'ZEBRONICS Zeb - Fame 5 watt Laptop/Desktop Speaker', 'price': {'sell_price': '₹599', 'org_price': '₹849', 'discount':"29% off"}, 'clrTitle': 'Black, 2.0 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/mobile-tablet-speaker/e/f/j/por-1578-portronics-original-imagtaf2d2w3f4ry.jpeg?q=70', 'content': {'title': 'Portronics SoundDrum P Wireless with 6-7 hrs Playback T...', 'price': {'sell_price': '₹2,098', 'org_price': '₹3,499', 'discount':"40% off"}, 'clrTitle': 'Black, Stereo Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/m/n/x/-original-imah4jfdjj6g3jrn.jpeg?q=70', 'content': {'title': 'Mivi Fort H120 Soundbar, 120 Watts, 2.1 Channel, Multi-...', 'price': {'sell_price': '₹5,999', 'org_price': '₹19,999', 'discount':"70% off"}, 'clrTitle': 'Black, 5.1 Channel', 'other': ['No Cost EMI from ₹1,000/month']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/kiqbma80-0/speaker/mobile-tablet-speaker/u/s/g/bs5rm2-bk-mivi-original-imafyg8xbv9rfsnn.jpeg?q=70', 'content': {'title': 'Mivi Roam2 5 W Bluetooth Speaker', 'price': {'sell_price': '₹899', 'org_price': '₹2,999', 'discount':"70% off"}, 'clrTitle': 'Black, Mono Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/u/f/k/-original-imagtevgtbtauah7.jpeg?q=70', 'content': {'title': 'boAt Stone 350 Hulk Edition 10 W Bluetooth Speaker', 'price': {'sell_price': '₹1,699', 'org_price': '₹3,490', 'discount':"51% off"}, 'clrTitle': 'Green Fury, Mono Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/j/q/v/-original-imagtnpuctjgnzrx.jpeg?q=70', 'content': {'title': 'boAt Aavante Bar 3500 with Bass & Treble Controls, EQ M...', 'price': {'sell_price': '₹13,999', 'org_price': '₹44,990', 'discount':"68% off"}, 'clrTitle': 'Premium Black, 5.1 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/kingqkw0-0/speaker/mobile-tablet-speaker/s/8/i/stone-350-boat-original-imafyebfuaumdezs.jpeg?q=70', 'content': {'title': 'boAt Stone 350 10 W Bluetooth Speaker', 'price': {'sell_price': '₹1,699', 'org_price': '₹3,490', 'discount':"51% off"}, 'clrTitle': 'Black, Mono Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/s/g/e/-original-imahy4y8heh2dbbr.jpeg?q=70', 'content': {'title': 'boAt Aavante Bar A1040 w/ Attractive Design, EQ Modes &...', 'price': {'sell_price': '₹3,999', 'org_price': '₹9,990', 'discount':"59% off"}, 'clrTitle': 'Premium Black, 2.1 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/a/c/e/-original-imahfg2nhxkmyshb.jpeg?q=70', 'content': {'title': 'GOVO GOSURROUND 950 | 260 W Bluetooth Soundbar', 'price': {'sell_price': '₹7,999', 'org_price': '₹24,999', 'discount':"68% off"}, 'clrTitle': 'Platinum Black, 5.1 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/v/o/a/-original-imah4jfdkdxnk2fg.jpeg?q=70', 'content': {'title': 'Mivi Fort H160 Soundbar, 160 Watts, 2.1 Channel, Multi-...', 'price': {'sell_price': '₹8,999', 'org_price': '₹25,999', 'discount':"65% off"}, 'clrTitle': 'Black, 5.1 Channel', 'other': ['No Cost EMI from ₹1,500/month']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/mobile-tablet-speaker/s/w/n/por-1578-portronics-original-imagtq36fg6sxzn9.jpeg?q=70', 'content': {'title': 'Portronics SoundDrum P Wireless with 6-7 hrs Playback T...', 'price': {'sell_price': '₹2,399', 'org_price': '₹3,999', 'discount':"40% off"}, 'clrTitle': 'Green, Stereo Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/laptop-desktop-speaker/c/i/z/zeb-warrior-zebronics-original-imah43f5jnzzhzsu.jpeg?q=70', 'content': {'title': 'ZEBRONICS ZEB-WARRIOR 10 W Laptop/Desktop Speaker', 'price': {'sell_price': '₹699', 'org_price': '₹1,249', 'discount':"44% off"}, 'clrTitle': 'Black, Black, 2.0 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/kiqbma80-0/speaker/mobile-tablet-speaker/j/l/p/bs5rm2-gn-mivi-original-imafyg8xdakhggu2.jpeg?q=70', 'content': {'title': 'Mivi Roam2 5 W Bluetooth Speaker', 'price': {'sell_price': '₹1,198', 'org_price': '₹2,999', 'discount':"60% off"}, 'clrTitle': 'Green, Mono Channel', 'other': ['Bank Offer']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/u/o/8/-original-imah2ggehx5ggumz.jpeg?q=70', 'content': {'title': 'Mivi Fort S38 With Sub woofer, 38W, BT v5.3, Surround S...', 'price': {'sell_price': '₹2,299', 'org_price': '₹10,999', 'discount':"79% off"}, 'clrTitle': 'Black, 2.1 Channel', 'other': ['Lowest price since launch']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/r/z/s/-original-imagz9cn93exxyrj.jpeg?q=70', 'content': {'title': 'boAt Aavante Bar 590 with RMS, Dual Passive Radiatior &...', 'price': {'sell_price': '₹1,999', 'org_price': '₹5,990', 'discount':"66% off"}, 'clrTitle': 'Pebble Black, 2.0 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/c/v/v/-original-imah4gpechxzhd9c.jpeg?q=70', 'content': {'title': 'boAt Aavante Bar 520 w/ Dual Passive Radiators,6 HRS Pl...', 'price': {'sell_price': '₹1,699', 'org_price': '₹3,990', 'discount':"57% off"}, 'clrTitle': 'Charcoal Black, 2.0 Channel', 'other': ['Daily Saver']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/kpzt7680/speaker/mobile-tablet-speaker/c/7/o/sounddrum-1-por-1327-portronics-original-imag43tcuz8swymc.jpeg?q=70', 'content': {'title': 'Portronics SoundDrum 1 10W TWS Portable, Inbuilt-FM & T...', 'price': {'sell_price': '₹1,199', 'org_price': '₹2,499', 'discount':"52% off"}, 'clrTitle': 'Blue, Mono Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/kmkxbww0/speaker/laptop-desktop-speaker/7/x/u/warrior-ii-2-0-channel-usb-speaker-led-lights-with-usb-powered-original-imagfg3h9azuzsxt.jpeg?q=70', 'content': {'title': 'ZEBRONICS WARRIOR II USB , LED LIGHTS WITH POWERED AND ...', 'price': {'sell_price': '₹649', 'org_price': '₹1,399', 'discount':"53% off"}, 'clrTitle': 'Black, 2.0 Channel', 'other': ['Daily Saver']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/kiqbma80-0/speaker/mobile-tablet-speaker/k/4/j/bs5rm2-rd-mivi-original-imafyg8xtrt4tywk.jpeg?q=70', 'content': {'title': 'Mivi Roam2 5 W Bluetooth Speaker', 'price': {'sell_price': '₹1,199', 'org_price': '₹2,999', 'discount':"60% off"}, 'clrTitle': 'Red, Mono Channel', 'other': ['Bank Offer']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/t/b/y/-original-imah4d3shajmeddh.jpeg?q=70', 'content': {'title': 'Mivi Fort H550 Soundbar, 550 Watts, 5.1 Channel, Multi-...', 'price': {'sell_price': '₹9,999', 'org_price': '₹39,999', 'discount':"75% off"}, 'clrTitle': 'Black, 5.1 Channel', 'other': ['No Cost EMI from ₹1,667/month']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/b/1/d/-original-imagqd2dzewdheez.jpeg?q=70', 'content': {'title': "GOVO GOSURROUND 900 |200W | 2.1 with 6.5'' Wired Subwoo...", 'price': {'sell_price': '₹6,599', 'org_price': '₹17,999', 'discount':"63% off"}, 'clrTitle': 'Platinum Black, 2.1 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/kingqkw0-0/speaker/mobile-tablet-speaker/u/1/2/stone-350-boat-original-imafyebfjguufap8.jpeg?q=70', 'content': {'title': 'boAt Stone 350 10 W Bluetooth Speaker', 'price': {'sell_price': '₹1,699', 'org_price': '₹3,490', 'discount':"51% off"}, 'clrTitle': 'Blue, Mono Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/shopsy-speaker/9/x/b/yes-16-soundbar-pro-surround-hd-sound-c-type-16-watt-1500mah-original-imahfyqtjmpfrbma.jpeg?q=70', 'content': {'title': 'MEGABAR Soundbar Pro 16W Speaker Party Light Speaker Wa...', 'price': {'sell_price': '₹899', 'org_price': '₹2,599', 'discount':"65% off"}, 'clrTitle': 'Black, 5.2 Channel', 'other': ['Lowest Price in 30 days']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/k/x/s/-original-imagszffm6qygvgb.jpeg?q=70', 'content': {'title': "GOVO GOSURROUND 750 |with 5.25'' Wired Subwoofer 120 W ...", 'price': {'sell_price': '₹5,499', 'org_price': '₹15,999', 'discount':"65% off"}, 'clrTitle': 'Platinum Black, 2.1 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/l0r1j0w0/speaker/u/s/u/-original-imagch7jmd9c9v7e.jpeg?q=70', 'content': {'title': 'Mivi Fort S100 with 2 in-built subwoofers, Made in Indi...', 'price': {'sell_price': '₹5,499', 'org_price': '₹9,999', 'discount':"45% off"}, 'clrTitle': 'Black, 2.2 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/y/r/i/-original-imagt4wcgmzdrhqv.jpeg?q=70', 'content': {'title': 'boAt Aavante Bar 480 with 7 HRS Playback, Dual Full Ran...', 'price': {'sell_price': '₹1,399', 'org_price': '₹3,490', 'discount':"59% off"}, 'clrTitle': 'Black, 2.0 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/x/q/b/-original-imah2d55jusy9p9t.jpeg?q=70', 'content': {'title': 'boAt Stone 350 Pro w/ Dynamic RGB LEDs, 12 HRS Playback...', 'price': {'sell_price': '₹1,999', 'org_price': '₹4,990', 'discount':"59% off"}, 'clrTitle': 'Raging Black, Mono Channel', 'other': ['Bank Offer']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/s/c/u/-original-imagg33vchvr6fw3.jpeg?q=70', 'content': {'title': 'Mivi Fort S200 with wired subwoofer, Made in India 200 ...', 'price': {'sell_price': '₹5,999', 'org_price': '₹19,999', 'discount':"70% off"}, 'clrTitle': 'Black, 2.1 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/kingqkw0-0/speaker/mobile-tablet-speaker/r/b/4/stone-350-boat-original-imafyebgtg74sghe.jpeg?q=70', 'content': {'title': 'boAt Stone 350 10 W Bluetooth Speaker', 'price': {'sell_price': '₹1,699', 'org_price': '₹3,490', 'discount':"51% off"}, 'clrTitle': 'Red, Mono Channel', 'other': ['Bank Offer']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/s/4/6/-original-imagz6kn77uzz9t3.jpeg?q=70', 'content': {'title': 'SONY HT-S20R 5.1ch Home Theatre with Dolby Digital, Sub...', 'price': {'sell_price': '₹17,190', 'org_price': '₹19,990', 'discount':"14% off"}, 'clrTitle': 'Black, 5.1 Channel', 'other': ['Save extra with combo offers']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/kplisnk0/speaker/mobile-tablet-speaker/8/t/m/bs5pl-bl-mivi-original-imag3sgm77an79j7.jpeg?q=70', 'content': {'title': 'Mivi Play 5 W Portable Bluetooth Speaker', 'price': {'sell_price': '₹799', 'org_price': '₹1,999', 'discount':"60% off"}, 'clrTitle': 'Blue, Mono Channel', 'other': ['Daily Saver']}},
// {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/speaker/n/s/7/-original-imah2d55jh6ryzjz.jpeg?q=70', 'content': {'title': 'boAt Stone 350 Pro w/ Dynamic RGB LEDs, 12 HRS Playback...', 'price': {'sell_price': '₹1,999', 'org_price': '₹4,990', 'discount':"59% off"}, 'clrTitle': 'Vibing Blue, Mono Channel', 'other': ['Bank Offer']}},
//  ]

// const keyboard=[{'url': 'https://rukminim2.flixcart.com/image/612/612/kwmfqfk0/musical-keyboard/i/1/3/49-key-piano-keyboard-toy-for-kids-dc-power-option-recording-original-imag99kzdf3uqddc.jpeg?q=70', 'content': {'title': 'HK ENTERPRISES OFFICIAL 49 Key Piano Keyboard Toy for K...', 'price': {'sell_price': '₹1,218', 'org_price': '₹1,999', 'discount': '39% off'}, 'clrTitle': '49 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/5/l/t/61-0-75-electronic-digital-piano-keyboard-61-keys-multi-function-original-imah48wacmndvkxz.jpeg?q=70', 'content': {'title': 'HK ENTERPRISES OFFICIAL Portable Electronic Digital Pia...', 'price': {'sell_price': '₹2,293', 'org_price': '₹3,999', 'discount': '42% off'}, 'clrTitle': '61 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/a/z/d/37-0-45-37-keys-beston-original-imagyqf8tfvn9xzy.jpeg?q=70', 'content': {'title': 'BESTON 37 Keys Piano Toy with Microphone, USB Power Cab...', 'price': {'sell_price': '₹509', 'org_price': '₹1,799', 'discount': '71% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/kt4ozgw0/musical-keyboard/l/w/h/a-02-samenterprise-original-imag6jtrjwkrhykg.jpeg?q=70', 'content': {'title': 'SAMENTERPRISE A-02 37 Key Piano Keyboard Toy for Kids w...', 'price': {'sell_price': '₹530', 'org_price': '₹1,999', 'discount': '73% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/8/r/d/37-0-4-piano-keyboard-toy-kids-with-mic-dc-power-option-original-imah2hztcfxubkwh.jpeg?q=70', 'content': {'title': 'Sai Store Piano Keyboard Toy Kids with Mic Dc Power Opt...', 'price': {'sell_price': '₹525', 'org_price': '₹1,999', 'discount': '73% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/3/n/s/61-0-3-int-kb-intern-original-imagzzggcyahaqpn.jpeg?q=70', 'content': {'title': 'intern INT-KB 61 Keys Touch Response Portable Piano Key...', 'price': {'sell_price': '₹2,899', 'org_price': '₹4,995', 'discount': '41% off'}, 'clrTitle': '61 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/x/a/l/37-0-6-37-keys-portable-piano-keyboard-piano-keyboard-toy-kids-original-imah4zebfhnfyajb.jpeg?q=70', 'content': {'title': 'intern 37 Keys Portable Piano Keyboard Piano Keyboard T...', 'price': {'sell_price': '₹1,208', 'org_price': '₹1,999', 'discount': '39% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/w/e/6/25-0-2-mini-baby-22-key-piano-playing-toy-kids-piano-music-original-imagxgc45ph6nrz7.jpeg?q=70', 'content': {'title': 'KAVANA Mini Baby 22 Key Piano Playing Toy/ Kids Piano M...', 'price': {'sell_price': '₹292', 'org_price': '₹899', 'discount': '67% off'}, 'clrTitle': '25 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/h/v/n/37-0-2-a128-piano-keyboard-with-recording-mic-mobile-charger-original-imah3wpfgguypzb7.jpeg?q=70', 'content': {'title': 'Nilesawar A128 Piano Keyboard with Recording ,Mic & Mob...', 'price': {'sell_price': '₹675', 'org_price': '₹1,699', 'discount': '60% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/kcc9q4w0/musical-toy/g/3/8/37-key-bigfun-piano-keyboard-toy-for-kids-with-mic-dc-power-original-imafthkxdaxm5cyn.jpeg?q=70', 'content': {'title': 'Shiv MUSICAL KEY 37 Battery Operated/Mobile Charger Pow...', 'price': {'sell_price': '₹675', 'org_price': '₹1,800', 'discount': '62% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/kph8h3k0/musical-keyboard/p/b/d/electronic-piano-keyboard-toy-with-dc-power-option-recording-and-original-imag3pb9urr4gaqq.jpeg?q=70', 'content': {'title': 'HK ENTERPRISES OFFICIAL Piano Keyboard Toy for Kids wit...', 'price': {'sell_price': '₹675', 'org_price': '₹1,932', 'discount': '65% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/9/r/z/37-0-4-piano-keyboard-piano-for-kids-with-microphone-portable-original-imagrncfkfwzrzth.jpeg?q=70', 'content': {'title': 'KAVANA Electronic Piano Keyboard Recording and replay M...', 'price': {'sell_price': '₹553', 'org_price': '₹1,999', 'discount': '72% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-toy/b/v/u/kids-37-key-piano-keyboard-with-recording-mic-mobile-charger-original-imagh4hcfz3ghdbd.jpeg?q=70', 'content': {'title': 'SNM97 BF_430A1 Kids 37 Key Piano Keyboard with Recordin...', 'price': {'sell_price': '₹726', 'org_price': '₹999', 'discount': '27% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/ki6bgcw0-0/musical-toy/q/l/e/amp-cosset-pack-37-key-piano-keyboard-toy-with-mic-dc-power-original-imafyf7j3gjctmye.jpeg?q=70', 'content': {'title': 'BHALALA ENTERPRISE PIANIO 37 Key Piano Toy Keyboard for...', 'price': {'sell_price': '₹615', 'org_price': '₹1,999', 'discount': '69% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/t/3/j/37-0-45-piano37-istambh-original-imagkheup2wfwkzs.jpeg?q=70', 'content': {'title': 'ISTAMBH Piano toy Bigfun Piano with Usb Port/Microphone...', 'price': {'sell_price': '₹719', 'org_price': '₹7,999', 'discount': '91% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/kon887k0/musical-keyboard/m/v/g/37-keys-piano-keyboard-toy-with-microphone-usb-power-cable-sound-original-imag3fr6b36dyzyn.jpeg?q=70', 'content': {'title': 'dwarikadhish enterprise 37 Keys Piano Keyboard Toy with...', 'price': {'sell_price': '₹624', 'org_price': '₹1,999', 'discount': '68% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/kebpqq80/musical-keyboard/j/h/h/37-keys-nj-fashion-original-imafvyhrjeuah2ge.jpeg?q=70', 'content': {'title': 'NJ FASHION 37 Keys 37 Keys Piano Keyboard Toy Sound Rec...', 'price': {'sell_price': '₹567', 'org_price': '₹1,999', 'discount': '71% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-toy/6/f/p/2-in-1-baby-piano-xylophone-toy-8-multicolored-key-keyboard-original-imahyz5wwhn7xuwu.jpeg?q=70', 'content': {'title': 'RUDOLF 2 in 1 Musical Melody & Educational Piano Xyloph...', 'price': {'sell_price': '₹404', 'org_price': '₹1,999', 'discount': '79% off'}, 'clrTitle': '8 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/p/s/f/37-0-2-a276-kids-piano-keyboard-piano-for-kids-with-microphone-original-imah3sc2rgqayfbr.jpeg?q=70', 'content': {'title': 'Shamsa A276 Kids Piano Keyboard, Piano for Kids with Mi...', 'price': {'sell_price': '₹675', 'org_price': '₹1,699', 'discount': '60% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/ku04o7k0/musical-keyboard/v/g/d/37-key-piano-keyboard-toy-for-boys-and-girls-with-mic-dc-power-original-imag77stgythbdzn.jpeg?q=70', 'content': {'title': 'Devta 37 Key Piano Keyboard Toy for Boys and Girls with...', 'price': {'sell_price': '₹675', 'org_price': '₹1,999', 'discount': '66% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/o/p/j/61-2-8-psr-f52-with-blueberry-yamaha-original-imah4y9mtywabcqn.jpeg?q=70', 'content': {'title': 'YAMAHA PSR F52 With Blueberry KB-40 Bag and R-12IN Stan...', 'price': {'sell_price': '₹9,040', 'org_price': '₹12,880', 'discount': '29% off'}, 'clrTitle': '61 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/r/m/m/49-0-65-49-key-piano-keyboard-toy-for-kids-p36-just97-original-imagqr3sbw9ghgkz.jpeg?q=70', 'content': {'title': 'Just97 49 Key Piano Keyboard Toy for Kids P36 dc Power ...', 'price': {'sell_price': '₹1,394', 'org_price': '₹2,499', 'discount': '44% off'}, 'clrTitle': '49 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/1/v/u/37-0-4-37-keys-electronic-piano-keyboard-with-led-display-original-imagh42tzaq7zm8f.jpeg?q=70', 'content': {'title': 'Just97 37 keys Electronic Piano Keyboard with LED Displ...', 'price': {'sell_price': '₹732', 'org_price': '₹2,999', 'discount': '75% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/t/h/v/37-0-45-bigfun-bf-430a1-piano-toy-with-microphone-sound-original-imah4cgzk6ngyhgg.jpeg?q=70', 'content': {'title': 'Zuurvi Bigfun BF_430A1 Piano Toy with Microphone | Soun...', 'price': {'sell_price': '₹675', 'org_price': '₹1,299', 'discount': '48% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/6/m/8/37-0-43-toybucket-430a1-musical-instrument-piano-toy-with-original-imah4y8uuwwxqcfv.jpeg?q=70', 'content': {'title': 'Zuurvi ToyBucket 430A1 Musical Instrument Piano Toy wit...', 'price': {'sell_price': '₹675', 'org_price': '₹1,299', 'discount': '48% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/ke353m80/musical-toy/7/y/e/37-key-piano-keyboard-toy-for-kids-with-mic-dc-power-option-original-imafuuzbp9txddyu.jpeg?q=70', 'content': {'title': 'BITTU Musical keypoard piano -01 Piano Keyboard Toy 37 ...', 'price': {'sell_price': '₹689', 'org_price': '₹1,618', 'discount': '57% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/k/a/s/37-0-4-big-fun-piano-kids-and-adult-piano-keyboard-piano-for-original-imagrne2mgwxzx35.jpeg?q=70', 'content': {'title': 'KAVANA Big Fun Piano | Kids and Adult Piano Keyboard | ...', 'price': {'sell_price': '₹600', 'org_price': '₹1,999', 'discount': '69% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/i/i/d/37-0-4-37-key-piano-keyboard-toy-for-kids-p14-just97-original-imagqr67hukbf748.jpeg?q=70', 'content': {'title': 'Just97 37 Key Piano Keyboard Toy for Kids P14 37 Key Pi...', 'price': {'sell_price': '₹725', 'org_price': '₹2,499', 'discount': '70% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/k/n/j/25-0-2-the-amazing-music-keyboard-piano-for-3-age-kavana-original-imagxm55s6cnnuua.jpeg?q=70', 'content': {'title': 'KAVANA The Amazing Music Keyboard (Piano) for 3+ Age Th...', 'price': {'sell_price': '₹292', 'org_price': '₹899', 'discount': '67% off'}, 'clrTitle': '25 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/v/w/z/37-0-3-musical-keypoard-piano-01-white-devil-original-imah4byhfqwm7uwz.jpeg?q=70', 'content': {'title': 'White Devil Musical keypoard piano -01 Musical keypoard...', 'price': {'sell_price': '₹549', 'org_price': '₹1,599', 'discount': '65% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/e/g/s/37-0-4-kids-keyboard-piano-recording-and-replay-music-piano-original-imahfyuqvyggsrsf.jpeg?q=70', 'content': {'title': 'KAVANA Kids Keyboard Piano, Recording and replay Music ...', 'price': {'sell_price': '₹642', 'org_price': '₹1,999', 'discount': '67% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/u/m/c/37-0-4-kids-piano-keyboard-with-microphone-portable-electronic-original-imagrmht7b6hjedp.jpeg?q=70', 'content': {'title': 'KAVANA Kids Piano Keyboard,with Microphone Portable Ele...', 'price': {'sell_price': '₹558', 'org_price': '₹1,999', 'discount': '72% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/klwmufk0/musical-keyboard/x/7/v/electronic-piano-keyboard-with-37-keys-and-with-microphone-dc-original-imagyxgjvbaujjny.jpeg?q=70', 'content': {'title': 'PEZYOX Electronic Piano Keyboard with 37 Keys and with ...', 'price': {'sell_price': '₹583', 'org_price': '₹1,499', 'discount': '61% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/x/o/f/61-3-4-f-51-yamaha-original-imah3d3zgyfmaesr.jpeg?q=70', 'content': {'title': 'YAMAHA F52 Yamaha PSR-F52 Portable Keyboard with 61 Key...', 'price': {'sell_price': '₹8,540', 'org_price': '₹12,845', 'discount': '33% off'}, 'clrTitle': '61 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-toy/j/s/a/37-keys-kids-and-adult-piano-keyboard-with-microphone-for-original-imagpzpurmmd2fcd.jpeg?q=70', 'content': {'title': 'Uvasaggaharam Musical Electronic Mini Keys BF-430A1 37 ...', 'price': {'sell_price': '₹725', 'org_price': '₹1,499', 'discount': '51% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/k2gh30w0/musical-keyboard/b/3/k/bf-403-yodnso-original-imafjtpynpybhhvf.jpeg?q=70', 'content': {'title': 'YODNSO BF-403 37 KEYS MUSICAL PIANO/TOY/INSTRUMENT Anal...', 'price': {'sell_price': '₹675', 'org_price': '₹1,447', 'discount': '53% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/e/m/c/37-0-45-keyboard-piano-gvp-toys-original-imah4zugkxh7aabj.jpeg?q=70', 'content': {'title': 'GVP Toys Keyboard Piano Keyboard Piano 37 Keys Keyboard...', 'price': {'sell_price': '₹739', 'org_price': '₹1,599', 'discount': '53% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/u/b/2/37-0-4-kids-37-key-piano-keyboard-with-recording-mic-mobile-original-imahffhberjkeda3.jpeg?q=70', 'content': {'title': 'AS TRADERS Kids 37 Key Piano Keyboard with Recording ,M...', 'price': {'sell_price': '₹675', 'org_price': '₹1,999', 'discount': '66% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-toy/p/h/3/kids-piano-keyboard-piano-for-kids-with-microphone-portable-original-imah3xx2kshxdy6n.jpeg?q=70', 'content': {'title': 'Haulsale BF-430 37 Key Piano Keyboard Toy with Power Op...', 'price': {'sell_price': '₹725', 'org_price': '₹1,999', 'discount': '63% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/l1ch4sw0/musical-keyboard/5/g/t/0-9-bf-430a1-royaldeals-rd-original-imagcxr2nnpkgg3y.jpeg?q=70', 'content': {'title': 'ROYALDEALS - RD BF_430A1 BIGFUN Piano Keyboard Toy with...', 'price': {'sell_price': '₹623', 'org_price': '₹1,999', 'discount': '68% off'}, 'clrTitle': '37 Keys'}},
//     ]
// const watches=[{'url': 'https://rukminim2.flixcart.com/image/612/612/kwmfqfk0/musical-keyboard/i/1/3/49-key-piano-keyboard-toy-for-kids-dc-power-option-recording-original-imag99kzdf3uqddc.jpeg?q=70', 'content': {'title': 'HK ENTERPRISES OFFICIAL 49 Key Piano Keyboard Toy for K...', 'price': {'sell_price': '₹1,218', 'org_price': '₹1,999', 'discount': '39% off'}, 'clrTitle': '49 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/5/l/t/61-0-75-electronic-digital-piano-keyboard-61-keys-multi-function-original-imah48wacmndvkxz.jpeg?q=70', 'content': {'title': 'HK ENTERPRISES OFFICIAL Portable Electronic Digital Pia...', 'price': {'sell_price': '₹2,293', 'org_price': '₹3,999', 'discount': '42% off'}, 'clrTitle': '61 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/a/z/d/37-0-45-37-keys-beston-original-imagyqf8tfvn9xzy.jpeg?q=70', 'content': {'title': 'BESTON 37 Keys Piano Toy with Microphone, USB Power Cab...', 'price': {'sell_price': '₹509', 'org_price': '₹1,799', 'discount': '71% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/kt4ozgw0/musical-keyboard/l/w/h/a-02-samenterprise-original-imag6jtrjwkrhykg.jpeg?q=70', 'content': {'title': 'SAMENTERPRISE A-02 37 Key Piano Keyboard Toy for Kids w...', 'price': {'sell_price': '₹530', 'org_price': '₹1,999', 'discount': '73% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/8/r/d/37-0-4-piano-keyboard-toy-kids-with-mic-dc-power-option-original-imah2hztcfxubkwh.jpeg?q=70', 'content': {'title': 'Sai Store Piano Keyboard Toy Kids with Mic Dc Power Opt...', 'price': {'sell_price': '₹525', 'org_price': '₹1,999', 'discount': '73% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/3/n/s/61-0-3-int-kb-intern-original-imagzzggcyahaqpn.jpeg?q=70', 'content': {'title': 'intern INT-KB 61 Keys Touch Response Portable Piano Key...', 'price': {'sell_price': '₹2,899', 'org_price': '₹4,995', 'discount': '41% off'}, 'clrTitle': '61 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/x/a/l/37-0-6-37-keys-portable-piano-keyboard-piano-keyboard-toy-kids-original-imah4zebfhnfyajb.jpeg?q=70', 'content': {'title': 'intern 37 Keys Portable Piano Keyboard Piano Keyboard T...', 'price': {'sell_price': '₹1,208', 'org_price': '₹1,999', 'discount': '39% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/w/e/6/25-0-2-mini-baby-22-key-piano-playing-toy-kids-piano-music-original-imagxgc45ph6nrz7.jpeg?q=70', 'content': {'title': 'KAVANA Mini Baby 22 Key Piano Playing Toy/ Kids Piano M...', 'price': {'sell_price': '₹292', 'org_price': '₹899', 'discount': '67% off'}, 'clrTitle': '25 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/h/v/n/37-0-2-a128-piano-keyboard-with-recording-mic-mobile-charger-original-imah3wpfgguypzb7.jpeg?q=70', 'content': {'title': 'Nilesawar A128 Piano Keyboard with Recording ,Mic & Mob...', 'price': {'sell_price': '₹675', 'org_price': '₹1,699', 'discount': '60% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/kcc9q4w0/musical-toy/g/3/8/37-key-bigfun-piano-keyboard-toy-for-kids-with-mic-dc-power-original-imafthkxdaxm5cyn.jpeg?q=70', 'content': {'title': 'Shiv MUSICAL KEY 37 Battery Operated/Mobile Charger Pow...', 'price': {'sell_price': '₹675', 'org_price': '₹1,800', 'discount': '62% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/kph8h3k0/musical-keyboard/p/b/d/electronic-piano-keyboard-toy-with-dc-power-option-recording-and-original-imag3pb9urr4gaqq.jpeg?q=70', 'content': {'title': 'HK ENTERPRISES OFFICIAL Piano Keyboard Toy for Kids wit...', 'price': {'sell_price': '₹675', 'org_price': '₹1,932', 'discount': '65% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/9/r/z/37-0-4-piano-keyboard-piano-for-kids-with-microphone-portable-original-imagrncfkfwzrzth.jpeg?q=70', 'content': {'title': 'KAVANA Electronic Piano Keyboard Recording and replay M...', 'price': {'sell_price': '₹553', 'org_price': '₹1,999', 'discount': '72% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-toy/b/v/u/kids-37-key-piano-keyboard-with-recording-mic-mobile-charger-original-imagh4hcfz3ghdbd.jpeg?q=70', 'content': {'title': 'SNM97 BF_430A1 Kids 37 Key Piano Keyboard with Recordin...', 'price': {'sell_price': '₹726', 'org_price': '₹999', 'discount': '27% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/ki6bgcw0-0/musical-toy/q/l/e/amp-cosset-pack-37-key-piano-keyboard-toy-with-mic-dc-power-original-imafyf7j3gjctmye.jpeg?q=70', 'content': {'title': 'BHALALA ENTERPRISE PIANIO 37 Key Piano Toy Keyboard for...', 'price': {'sell_price': '₹615', 'org_price': '₹1,999', 'discount': '69% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/t/3/j/37-0-45-piano37-istambh-original-imagkheup2wfwkzs.jpeg?q=70', 'content': {'title': 'ISTAMBH Piano toy Bigfun Piano with Usb Port/Microphone...', 'price': {'sell_price': '₹719', 'org_price': '₹7,999', 'discount': '91% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/kon887k0/musical-keyboard/m/v/g/37-keys-piano-keyboard-toy-with-microphone-usb-power-cable-sound-original-imag3fr6b36dyzyn.jpeg?q=70', 'content': {'title': 'dwarikadhish enterprise 37 Keys Piano Keyboard Toy with...', 'price': {'sell_price': '₹624', 'org_price': '₹1,999', 'discount': '68% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/kebpqq80/musical-keyboard/j/h/h/37-keys-nj-fashion-original-imafvyhrjeuah2ge.jpeg?q=70', 'content': {'title': 'NJ FASHION 37 Keys 37 Keys Piano Keyboard Toy Sound Rec...', 'price': {'sell_price': '₹567', 'org_price': '₹1,999', 'discount': '71% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-toy/6/f/p/2-in-1-baby-piano-xylophone-toy-8-multicolored-key-keyboard-original-imahyz5wwhn7xuwu.jpeg?q=70', 'content': {'title': 'RUDOLF 2 in 1 Musical Melody & Educational Piano Xyloph...', 'price': {'sell_price': '₹404', 'org_price': '₹1,999', 'discount': '79% off'}, 'clrTitle': '8 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/p/s/f/37-0-2-a276-kids-piano-keyboard-piano-for-kids-with-microphone-original-imah3sc2rgqayfbr.jpeg?q=70', 'content': {'title': 'Shamsa A276 Kids Piano Keyboard, Piano for Kids with Mi...', 'price': {'sell_price': '₹675', 'org_price': '₹1,699', 'discount': '60% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/ku04o7k0/musical-keyboard/v/g/d/37-key-piano-keyboard-toy-for-boys-and-girls-with-mic-dc-power-original-imag77stgythbdzn.jpeg?q=70', 'content': {'title': 'Devta 37 Key Piano Keyboard Toy for Boys and Girls with...', 'price': {'sell_price': '₹675', 'org_price': '₹1,999', 'discount': '66% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/o/p/j/61-2-8-psr-f52-with-blueberry-yamaha-original-imah4y9mtywabcqn.jpeg?q=70', 'content': {'title': 'YAMAHA PSR F52 With Blueberry KB-40 Bag and R-12IN Stan...', 'price': {'sell_price': '₹9,040', 'org_price': '₹12,880', 'discount': '29% off'}, 'clrTitle': '61 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/r/m/m/49-0-65-49-key-piano-keyboard-toy-for-kids-p36-just97-original-imagqr3sbw9ghgkz.jpeg?q=70', 'content': {'title': 'Just97 49 Key Piano Keyboard Toy for Kids P36 dc Power ...', 'price': {'sell_price': '₹1,394', 'org_price': '₹2,499', 'discount': '44% off'}, 'clrTitle': '49 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/1/v/u/37-0-4-37-keys-electronic-piano-keyboard-with-led-display-original-imagh42tzaq7zm8f.jpeg?q=70', 'content': {'title': 'Just97 37 keys Electronic Piano Keyboard with LED Displ...', 'price': {'sell_price': '₹732', 'org_price': '₹2,999', 'discount': '75% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/t/h/v/37-0-45-bigfun-bf-430a1-piano-toy-with-microphone-sound-original-imah4cgzk6ngyhgg.jpeg?q=70', 'content': {'title': 'Zuurvi Bigfun BF_430A1 Piano Toy with Microphone | Soun...', 'price': {'sell_price': '₹675', 'org_price': '₹1,299', 'discount': '48% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/6/m/8/37-0-43-toybucket-430a1-musical-instrument-piano-toy-with-original-imah4y8uuwwxqcfv.jpeg?q=70', 'content': {'title': 'Zuurvi ToyBucket 430A1 Musical Instrument Piano Toy wit...', 'price': {'sell_price': '₹675', 'org_price': '₹1,299', 'discount': '48% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/ke353m80/musical-toy/7/y/e/37-key-piano-keyboard-toy-for-kids-with-mic-dc-power-option-original-imafuuzbp9txddyu.jpeg?q=70', 'content': {'title': 'BITTU Musical keypoard piano -01 Piano Keyboard Toy 37 ...', 'price': {'sell_price': '₹689', 'org_price': '₹1,618', 'discount': '57% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/k/a/s/37-0-4-big-fun-piano-kids-and-adult-piano-keyboard-piano-for-original-imagrne2mgwxzx35.jpeg?q=70', 'content': {'title': 'KAVANA Big Fun Piano | Kids and Adult Piano Keyboard | ...', 'price': {'sell_price': '₹600', 'org_price': '₹1,999', 'discount': '69% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/i/i/d/37-0-4-37-key-piano-keyboard-toy-for-kids-p14-just97-original-imagqr67hukbf748.jpeg?q=70', 'content': {'title': 'Just97 37 Key Piano Keyboard Toy for Kids P14 37 Key Pi...', 'price': {'sell_price': '₹725', 'org_price': '₹2,499', 'discount': '70% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/k/n/j/25-0-2-the-amazing-music-keyboard-piano-for-3-age-kavana-original-imagxm55s6cnnuua.jpeg?q=70', 'content': {'title': 'KAVANA The Amazing Music Keyboard (Piano) for 3+ Age Th...', 'price': {'sell_price': '₹292', 'org_price': '₹899', 'discount': '67% off'}, 'clrTitle': '25 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/v/w/z/37-0-3-musical-keypoard-piano-01-white-devil-original-imah4byhfqwm7uwz.jpeg?q=70', 'content': {'title': 'White Devil Musical keypoard piano -01 Musical keypoard...', 'price': {'sell_price': '₹549', 'org_price': '₹1,599', 'discount': '65% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/e/g/s/37-0-4-kids-keyboard-piano-recording-and-replay-music-piano-original-imahfyuqvyggsrsf.jpeg?q=70', 'content': {'title': 'KAVANA Kids Keyboard Piano, Recording and replay Music ...', 'price': {'sell_price': '₹642', 'org_price': '₹1,999', 'discount': '67% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/u/m/c/37-0-4-kids-piano-keyboard-with-microphone-portable-electronic-original-imagrmht7b6hjedp.jpeg?q=70', 'content': {'title': 'KAVANA Kids Piano Keyboard,with Microphone Portable Ele...', 'price': {'sell_price': '₹558', 'org_price': '₹1,999', 'discount': '72% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/klwmufk0/musical-keyboard/x/7/v/electronic-piano-keyboard-with-37-keys-and-with-microphone-dc-original-imagyxgjvbaujjny.jpeg?q=70', 'content': {'title': 'PEZYOX Electronic Piano Keyboard with 37 Keys and with ...', 'price': {'sell_price': '₹583', 'org_price': '₹1,499', 'discount': '61% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/x/o/f/61-3-4-f-51-yamaha-original-imah3d3zgyfmaesr.jpeg?q=70', 'content': {'title': 'YAMAHA F52 Yamaha PSR-F52 Portable Keyboard with 61 Key...', 'price': {'sell_price': '₹8,540', 'org_price': '₹12,845', 'discount': '33% off'}, 'clrTitle': '61 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-toy/j/s/a/37-keys-kids-and-adult-piano-keyboard-with-microphone-for-original-imagpzpurmmd2fcd.jpeg?q=70', 'content': {'title': 'Uvasaggaharam Musical Electronic Mini Keys BF-430A1 37 ...', 'price': {'sell_price': '₹725', 'org_price': '₹1,499', 'discount': '51% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/k2gh30w0/musical-keyboard/b/3/k/bf-403-yodnso-original-imafjtpynpybhhvf.jpeg?q=70', 'content': {'title': 'YODNSO BF-403 37 KEYS MUSICAL PIANO/TOY/INSTRUMENT Anal...', 'price': {'sell_price': '₹675', 'org_price': '₹1,447', 'discount': '53% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/e/m/c/37-0-45-keyboard-piano-gvp-toys-original-imah4zugkxh7aabj.jpeg?q=70', 'content': {'title': 'GVP Toys Keyboard Piano Keyboard Piano 37 Keys Keyboard...', 'price': {'sell_price': '₹739', 'org_price': '₹1,599', 'discount': '53% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-keyboard/u/b/2/37-0-4-kids-37-key-piano-keyboard-with-recording-mic-mobile-original-imahffhberjkeda3.jpeg?q=70', 'content': {'title': 'AS TRADERS Kids 37 Key Piano Keyboard with Recording ,M...', 'price': {'sell_price': '₹675', 'org_price': '₹1,999', 'discount': '66% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/xif0q/musical-toy/p/h/3/kids-piano-keyboard-piano-for-kids-with-microphone-portable-original-imah3xx2kshxdy6n.jpeg?q=70', 'content': {'title': 'Haulsale BF-430 37 Key Piano Keyboard Toy with Power Op...', 'price': {'sell_price': '₹725', 'org_price': '₹1,999', 'discount': '63% off'}, 'clrTitle': '37 Keys'}},
//     {'url': 'https://rukminim2.flixcart.com/image/612/612/l1ch4sw0/musical-keyboard/5/g/t/0-9-bf-430a1-royaldeals-rd-original-imagcxr2nnpkgg3y.jpeg?q=70', 'content': {'title': 'ROYALDEALS - RD BF_430A1 BIGFUN Piano Keyboard Toy with...', 'price': {'sell_price': '₹623', 'org_price': '₹1,999', 'discount': '68% off'}, 'clrTitle': '37 Keys'}},
//     ]

// AddDataController.addData(watches);




// step=>3

if (process.env.NODE_ENV == "production") {
    app.use(express.static("client/build"));
}




//Server Listening
app.listen(PORT, () => {

})









